VORTEX_MYSQL_IP: localhost
VORTEX_MYSQL_PORT: 3306
VORTEX_MYSQL_DATABASE: cloud_sample
VORTEX_MYSQL_USERNAME: root
VORTEX_MYSQL_PASSWORD: 123456

VORTEX_REDIS_IP: localhost
VORTEX_REDIS_PORT: 6379
VORTEX_REDIS_PASSWORD: 123456
VORTEX_REDIS_DATABASE: 0

VORTEX_NACOS: localhost:8848
VORTEX_NACOS_ENABLED: false
VORTEX_EUREKA: localhost:8761
VORTEX_EUREKA_ENABLED: false

VORTEX_GATEWAY: kanbandev.cloudhw.cn:8446
ACS_GATEWAY: kanbandev.cloudhw.cn:8446