VORTEX_MYSQL_IP: 192.168.1.246
VORTEX_MYSQL_PORT: 3309
VORTEX_MYSQL_USERNAME: root
VORTEX_MYSQL_PASSWORD: VortexInfo@2023
VORTEX_MYSQL_DATABASE: cloud_sample

VORTEX_REDIS_IP: 192.168.1.242
VORTEX_REDIS_PORT: 6397
VORTEX_REDIS_PASSWORD: Vortex_2023
VORTEX_REDIS_DATABASE: 0

VORTEX_NACOS: localhost:8848
VORTEX_NACOS_ENABLED: false
VORTEX_EUREKA_ENABLED: true
VORTEX_EUREKA: vortex:VortexInfo2023@192.168.1.239:20001

VORTEX_KAFKA: 192.168.1.239:9092
VORTEX_GATEWAY: 192.168.1.239:20002
ACS_GATEWAY: 192.168.1.239:20002
