// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { connect, useDispatch, useStore, useSelector, getDvaApp } from '/Users/shibin/code/hjy/zhsw/test4/frontend/src/.umi/plugin-dva';
// plugins types.d.ts
export * from '/Users/shibin/code/hjy/zhsw/test4/frontend/src/.umi/plugin-dva/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/shibin/code/hjy/zhsw/test4/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.53_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/shibin/code/hjy/zhsw/test4/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.53_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/shibin/code/hjy/zhsw/test4/frontend/node_modules/.pnpm/umi@4.6.53_@babel+core@7.29.0_@types+node@25.7.0_@types+react@18.3.28_eslint@8.35.0_jes_f6000967c7ab983bbc8581b4da2dc6d6/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
