// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { connect, useDispatch, useStore, useSelector } from '/Users/shibin/code/hjy/zhsw/test4/frontend/node_modules/.pnpm/@umijs+plugins@4.6.53_@babel+core@7.29.0_@types+react-dom@18.3.7_@types+react@18.3.28___9e79940c8ab58724634529f3594ef513/node_modules/@umijs/plugins/libs/dva.tsx';
export { getDvaApp } from './dva';
