// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/shibin/code/hjy/zhsw/test4/frontend/src/models/common';
import model_2 from '/Users/shibin/code/hjy/zhsw/test4/frontend/src/pages/demo/model';

export const models = {
model_1: { namespace: 'common', model: model_1 },
model_2: { namespace: 'demo.model', model: model_2 },
} as const
