// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/demo","title":"示例","parent":{"key":"DEMO_BASIC","name":"基础数据"},"parentId":"1","id":"2"},"3":{"path":"/403","title":"403","parentId":"1","id":"3"},"4":{"path":"*","title":"404","parentId":"1","id":"4"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.js')),
'2': React.lazy(() => import(/* webpackChunkName: "p__demo__index" */'@/pages/demo/index.js')),
'3': React.lazy(() => import(/* webpackChunkName: "p__403" */'@/pages/403.js')),
'4': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.js')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/shibin/code/hjy/zhsw/test4/frontend/src/layouts/index.js')),
},
  };
}
